// export const baseUrl = 'https://raw.githubusercontent.com/BelinChung/api-mock/master/HiApp'
// export const baseUrl = 'https://appserver.88mmmoney.com/appServer/'
export const baseUrl = 'https://appserver.mmzb.com/appServer/'
// export const baseUrl = 'http://192.168.10.92:8480/appServer/'
// export const baseUrl = 'http://appserver.mmzb.com/appServer/'
// export const baseUrl = 'http://192.168.10.164:8480/app-wap-personal/'
